---
title: "Data for districts weekly"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(fs)
  library(here)
  library(lubridate)
  library(readxl)
})
```

```{r}
save_path <- path(here(),"r_data")
```

```{r}
if(!dir_exists(save_path)) dir_create(save_path)
```




Read names of regions

```{r}
tmpdir <- tempdir()
download.file("https://www.statistik.at/verzeichnis/reglisten/gemliste_knz.xls",
              path(tmpdir,"gemliste_knz.xls"),
              quiet=TRUE)
read_excel(path(tmpdir,"gemliste_knz.xls"),skip=3) |>
  select(1:2) |>
  drop_na() |>
  rename(GKZ=1,
         Name=2) |>
  mutate_at(vars(GKZ),as.integer) ->
  namen_gemeinden
```


```{r}
download.file("https://www.statistik.at/verzeichnis/reglisten/polbezirke.xls",
              path(tmpdir,"polbezirke.xls"),
              quiet=TRUE)
read_excel(path(tmpdir,"polbezirke.xls"),skip=3) |>
  select(1:4) |>
  drop_na() |>
  rename(BundeslandID=1,
         Bundesland=2,
         BKZ=3,
         Name=4)|>
  mutate_at(vars(BundeslandID,BKZ),as.integer) |>
  mutate(Name=str_replace(Name,fixed("(")," (")) ->
  namen_bezirke

namen_bezirke |>
  select(1:2) |>
  distinct() |>
  bind_rows(
    tibble(
      BundeslandID=10,
      Bundesland="Österreich"
    )
  ) ->
  namen_bl
```



Read csv files from repository upt to year 2022

```{r}
2002:2022 |>
  map(
  \(i)suppressMessages(
    read_csv2(
      paste0(
      "https://data.statistik.gv.at/data/OGD_bevstandjbab2002_BevStand_",
      i,
      ".csv")))
  ) |> 
  reduce(bind_rows) |>
  mutate(Jahr=str_sub(`C-A10-0`,5,8) |> as.integer()) |>
  mutate(Geschlecht=str_sub(`C-C11-0`,5,5)) |>
  mutate(Geschlecht=ifelse(Geschlecht==1,"m","w")) |>
  mutate(Alter=str_sub(`C-GALTEJ112-0`,11,13)) |> 
  mutate(Alter=as.integer(Alter)-1) |>
  mutate(Alter=as.integer(Alter)) |>
  mutate(GKZ=str_sub(`C-GRGEMAKT-0`,10,14) |> as.integer()) |>
  mutate(pop=`F-ISIS-1` |> as.integer()) |>
  select(Jahr,GKZ,Alter,Geschlecht,pop) ->
  pop_GKZ_age_1y_gender_yearly
```

```{r}
pop_GKZ_age_1y_gender_yearly |>
  left_join(namen_gemeinden) ->
  pop_GKZ_age_1y_gender_yearly  
```


Save yearly data for communities (Gemeinden)

```{r}
save(pop_GKZ_age_1y_gender_yearly,
     file=path(save_path,
               "pop_GKZ_age_1y_gender_yearly.RData"))
```

Yearly data for disctices (Bezirke)

```{r}
pop_GKZ_age_1y_gender_yearly |>
  mutate(BKZ=floor(GKZ/100)) |>
  group_by(Jahr,BKZ,Alter,Geschlecht) |>
  summarise(pop=sum(pop)) |>
  ungroup() ->
  pop_BKZ_age_1y_gender_yearly
```

```{r}
pop_BKZ_age_1y_gender_yearly |>
  left_join(namen_bezirke |>
              select(BKZ,Name)) ->
  pop_BKZ_age_1y_gender_yearly
```

```{r}
save(pop_BKZ_age_1y_gender_yearly,
     file=path(here(),"r_data",
               "pop_BKZ_age_1y_gender_yearly.RData"))  
```



```{r}
paste(2002:2023,"12","31",sep="-") |>
  as.Date() |>
  keep(\(x)isoweek(x)==53) |>
  year() ->
  years_with_week_53
```



```{r}
expand_grid(
  Jahr= 2002:2022,
  Woche=1:52,
  BKZ = pop_BKZ_age_1y_gender_yearly |>
    pull(BKZ) |> unique(),
  Alter=pop_BKZ_age_1y_gender_yearly |>
    pull(Alter) |> unique(),
  Geschlecht=c("m","w")) |>
  mutate(Jahr_Woche=Jahr+(Woche-1)/52) |>
  arrange(Jahr,Woche,BKZ,Alter,Geschlecht,Jahr_Woche) ->
  interpolation_BKZ_input
```


```{r}
expand_grid(
  Jahr= 2002:2022,
  Woche=1:52,
  BKZ = pop_BKZ_age_1y_gender_yearly |>
    pull(BKZ) |> unique(),
  Alter=pop_BKZ_age_1y_gender_yearly |>
    pull(Alter) |> unique(),
  Geschlecht=c("m","w")) |>
  left_join(pop_BKZ_age_1y_gender_yearly) |>
  replace_na(list(pop=0)) |>
  mutate(pop=ifelse(Woche==1,pop,NA)) ->
  interpolation_BKZ_base
```



```{r}
interpolation_BKZ_input |>
  left_join(interpolation_BKZ_base # |>
) |>
  group_by(BKZ,Alter,Geschlecht) |>
  mutate(pop_new=approxfun(cur_data() |> 
                             filter(!is.na(pop)) |> 
                             pull(Jahr_Woche),
                           cur_data() |> 
                             filter(!is.na(pop)) |> 
                             pull(pop),
                           rule=2)(Jahr_Woche)
         ) |>
  ungroup() |>
  select(-pop) |>
  rename(pop=pop_new) |>
  select(Jahr,Woche,Jahr_Woche,everything()) |>
  select(-Jahr_Woche) ->
  pop_BKZ_age_1y_gender_weekly
```



```{r}
pop_BKZ_age_1y_gender_weekly |>
  bind_rows(
    pop_BKZ_age_1y_gender_weekly |>
    filter(Woche==1) |>
  mutate(Jahr=Jahr-1,
         Woche=53) |>
  filter(Jahr > min(Jahr)) |>
    filter(Jahr %in% years_with_week_53 |
             Woche < 53)
  ) |>
  arrange(Jahr,Woche,BKZ,Alter,Geschlecht) ->
pop_BKZ_age_1y_gender_weekly   
```




```{r}
date_year_week <-
  tibble(
    Datum =  
      seq(as.Date("2001-12-31"),as.Date("2023-01-06"),by="7 days")) |>
      mutate(Jahr=isoyear(Datum),
             Woche=isoweek(Datum))
    
```



```{r}
pop_BKZ_age_1y_gender_weekly |>
  left_join(date_year_week) |>
  select(Jahr,Woche,Datum,everything()) ->
pop_BKZ_age_1y_gender_weekly  
```



```{r}
pop_BKZ_age_1y_gender_weekly |>
  left_join(namen_bezirke |>
              select(BKZ,Name)) ->
  pop_BKZ_age_1y_gender_weekly
```



```{r}
save(pop_BKZ_age_1y_gender_weekly,
     file=path(save_path,
               "pop_BKZ_age_1y_gender_weekly.Rdata"))
```



```{r}
pop_BKZ_age_1y_gender_weekly |> 
  mutate(BundeslandID=floor(BKZ/100)) |>
  group_by(Jahr,Woche,Datum,BundeslandID,Alter,Geschlecht) |>
  summarise(pop=sum(pop)) |>
  ungroup() ->
  pop_bl_age_1y_gender_weekly   
```

```{r}
pop_bl_age_1y_gender_weekly |> 
  mutate(BundeslandID=10) |>
  group_by(Jahr,Woche,Datum,BundeslandID,Alter,Geschlecht) |>
  summarise(pop=sum(pop)) |>
  ungroup() ->
  pop_aut_age_1y_gender_weekly 
```

```{r}
pop_bl_age_1y_gender_weekly |>
  bind_rows(
  pop_aut_age_1y_gender_weekly 
  ) -> 
  pop_aut_bl_age_1y_gender_weekly  
```


```{r}
  pop_aut_bl_age_1y_gender_weekly  |>
  left_join(namen_bl) ->
  pop_aut_bl_age_1y_gender_weekly
```

```{r}
save(pop_aut_bl_age_1y_gender_weekly,
     file=path(save_path,
               "pop_aut_bl_age_1y_gender_weekly.Rdata"))
```

```{r}
pop_aut_bl_age_1y_gender_weekly |>
  group_by(Jahr,Woche,Datum,BundeslandID,Bundesland,Geschlecht) |>
  summarise(pop=sum(pop)) |>
  ungroup() ->
  pop_aut_bl_gender_weekly
```

```{r}
save(pop_aut_bl_gender_weekly,
     file=path(save_path,
               "pop_aut_bl_gender_weekly.Rdata"))
```


```{r}
pop_aut_bl_gender_weekly |>
  group_by(Jahr,Woche,Datum,BundeslandID,Bundesland) |>
  summarise(pop=sum(pop)) |>
  ungroup() ->
  pop_aut_bl_weekly
```


```{r}
save(pop_aut_bl_weekly,
     file=path(save_path,
               "pop_aut_bl_weekly.Rdata"))
```